### ISSUE TITLE
Help request link does not point to message

### ISSUE THREAD

**Issue by yantar92** [bzg/woof#25]
I tried to create a help request with custom request title "Help testing table alignment with variable-pitch/unicode fonts". The request showed up in https://updates.orgmode.org/, but the link [1] is incorrect:

    Message-ID <8735uos5yj.fsf@localhost>
    not found

    Perhaps try an external site:
    ...

Yet, the actual message is available in [2]

[1] https://orgmode.org/list/8735uos5yj.fsf@localhost/

[2] https://orgmode.org/list/8735uos5yj.fsf@localhost/T/#u

**Comment by bzg** [comment]
It is because the `public-inbox` instance on https://orgmode.org/list/ needs ~20 minutes to process new incoming emails.  You can check now, the link is working correctly.

**Comment by yantar92** [comment]
> You can check now, the link is working correctly.

But it is not... The link [1] is not working. The link [2] is working. Yet, link [1] is what is given in updates.orgmode.org

**Comment by bzg** [comment]
Weird, because https://orgmode.org/list/8735uos5yj.fsf@localhost/ is working fine here.

**Comment by yantar92** [comment]
It seems to be an issue with browser cache. Link is working again after browser restart. Sorry for the noise.
