### ISSUE TITLE
Send email notifications when action has been registered/rejected

### ISSUE THREAD

**Issue by yantar92** [bzg/woof#26]
It would be great if Woof provided feedback to the users trying to trigger an action:

1. When bug is confirmed, Woof could email the author of the confirmation back telling that confirmation has been registered. Or even better - if an author of confirmation does not CC some people in the thread, they could also be notified that the bug has been confirmed.
2. Same for fixed, but it may also be a good idea to email the bug reporter unconditionally to make sure that fix is not missed.
3. Patch/applied can use the same ideas as 1-2
4. Help, change, and release announcements could also provide a feedback, especially to avoid silent rejections when rights are not sufficient to announce releases
5. Also, probably not directly related to Woof, but first-time contributors to mailing list might get auto-reply with list rules, like waiting at least a month(?) before bumping the thread again and about message citation style.

**Comment by bzg** [comment]
Very good suggestions, thanks a lot!

**Comment by bzg** [comment]
Hi @yantar92, I've noted down this suggestion in my todo list.  As https://git.sr.ht/~bzg/woof becomes the main repository for developing `Woof!`, I'm disable issues from this repo.

I've also set https://lists.sr.ht/~bzg/woof to let people discuss features and report bugs or contribute patches.  As soon as the next version of `Woof!` is ready, I'll hook it on this mailing list (dogfood eating).
