### ISSUE TITLE
X-Woof-Delete: email=someone@somewhere.com ?

### ISSUE THREAD

**Issue by bzg** [bzg/woof#9]
And maybe other parameters.

Triggered only when the admin sends an email to the `Woof!` mailbox directly.

See https://github.com/bzg/woof/issues/5 for context.

**Comment by tecosaur** [comment]
I think it would also be quite nice to be able bulk-mark emails with the normal X-Woof-{Patch|Issue|etc.} headers. I'm not sure what a good way of doing this would be though.

Maybe this is best for another issue though?

**Comment by bzg** [comment]
`X-Woof-Issue` won't exist, as the idea of `Woof!` is precisely to stop calling everything an "issue" :)

Also, I think `X-Woof-Patch` should stay thread-based, as it is today.  Still, I get your point and the admins and maintainers should be able to close several patches without spamming the list, so let's have [maintainers](https://github.com/bzg/woof/issues/11).

`X-Woof-Delete` would be the only silent-only admin/maintainers-only administrative action.

- `email:email`: Delete entries created by `email`
- `older:date`: Delete entries older than `date`
- `match:regexp`: Delete entries with subject matching `match`

Note that the name of current `X-Woof-*` keywords expresses the *type* of entries that `Woof!` will list.

Introducing `X-Woof-Delete` is delicate because it introduces a new type of keywords, one that express the type of action performed - so I'll carefully think about this.

**Comment by bzg** [comment]
The previous comments is obsolete, as the Woof! rewrite took another direction.  But the feature in the title is implemented (and obviously needs testing), so I'm closing this.
